### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by ivanoff13** [Uminosachi/sd-webui-inpaint-anything#20]
https://i.postimg.cc/VkNDsTBf/2023-05-27-163504.jpg

**Comment by Uminosachi** [comment]
This issue might be due to insufficient CUDA memory. Here are some potential solutions:

* Try a smaller SAM size: SAM is available in three sizes. Use the Base size model (`sam_vit_b_01ec64.pth`).
* Disable unnecessary extensions: Other extensions might be consuming VRAM. Try turning off any you don't need.
  * You may want to check out the [Standalone version](https://github.com/Uminosachi/inpaint-anything) of Inpaint Anything.
* Reduce image size: Larger images consume more VRAM. Could you try reducing the size of your image?

**Comment by Uminosachi** [comment]
This issue appears to be the same as the 'CUDA out of memory' issue referenced in #22, so it will be closed.
