### ISSUE TITLE
 why cant we use from the already installed inpainting  models 

### ISSUE THREAD

**Issue by sahil1572** [Uminosachi/sd-webui-inpaint-anything#55]

**Comment by Uminosachi** [comment]
You can use the installed inpainting model in the following way: Click the `Get mask` button on the `Mask only` tab, then click the `Send to img2img inpaint` button. This will send both the image and mask to img2img tab on the web UI.

Since some users might not have an inpainting model, direct execution has not been implemented.

**Comment by Uminosachi** [comment]
In v1.9.0, I have added the function to search for inpainting models of the webUI and to display and run the Inpainting webui tab, if these models are found.

**Comment by Uminosachi** [comment]
Duplicate of #33

**Comment by Uminosachi** [comment]
The 'Inpainting webui' tab, which enables the use of the inpainting model saved in the web UI models directory, has been implemented. Therefore, this issue will be closed.
