### ISSUE TITLE
"Replace anything" functionality

### ISSUE THREAD

**Issue by sachit-menon** [Uminosachi/sd-webui-inpaint-anything#8]
Hi, thanks for this great extension! One of my main use cases is the "Replace Anything" feature which changes the background https://github.com/geekyutao/Inpaint-Anything#-replace-anything. Any chance this will be added/is easy to add? (I saw a related issue for "Remove Anything" but that's the inverse and is implemented differently.) 

I think this would be useful for a lot of people, who are just trying to use the vanilla inpaint function for this right now!

**Comment by Uminosachi** [comment]
Proposed Thank you. I have reviewed the "Replace Anything" implementation that you linked to, and it seems to be using the same Diffusers StableDiffusionInpaintPipeline as this repository. Therefore, the difference is in the mask specification. However, since the current implementation covers it well, I don't think it's necessary to add the feature.
